[package]
name = "rkyvdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rkyv = "0.7.38"
rocksdb = "0.18.0"
thiserror = "1.0.31"
